on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Commit subdir files
        run: |
          git config --global user.email "briangu33@gmail.com"
          git config --global user.name "Brian Gu"
          echo $(ls)
          cd submodule-test
          git init
          git remote add origin git@github.com:briangu33/submodule-test.git
          git add -A
          git commit -m "first commit"
          cd ../
      - name: Push subdir files
        uses: ad-m/github-push-action@master
        with:
          directory: submodule-test
          repository: briangu33/submodule-test
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
      - name: Hello world action step
        uses: ./.github/actions/copy-os-repo # Uses an action in the root directory
        id: hello
        with:
          who-to-greet: 'Panda Bear'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"