on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          path: main
      - name: Checkout public repo
        uses: actions/checkout@v2
        with:
          repository: briangu33/submodule-test
          path: public
      - name: Commit subdir files
        run: |
          echo $(ls main)
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          cd main/submodule-test
          cp -r ../../public/.git .
          git add -A
          git commit -m "update submodule-test"
      - name: Push subdir files
        uses: ad-m/github-push-action@master
        with:
          directory: public
          repository: briangu33/submodule-test
          github_token: ${{ secrets.SM_TEST_TOKEN }}
      - name: Hello world action step
        uses: ./.github/actions/copy-os-repo # Uses an action in the root directory
        id: hello
        with:
          who-to-greet: 'Panda Bear'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"